### ISSUE TITLE
Verificar el reporte

### ISSUE THREAD

**Issue by kala855** [dila93/HPC#1]
Muchachos hace falta información vital en cuanto a gráficas de tiempos en el README.md

**Comment by sebastian-ardila** [comment]
Hola profe, a que información se refiere?

**Comment by kala855** [comment]
No me salen las graficas dentro del README.md, deben verse en el markdown.

**Comment by fullarukad** [comment]
tan raro porque yo si las veo profe!, vamos a revisar bien eso a ver que pasa, sera que estamos haciendo algo mal en el git

**Comment by kala855** [comment]
Las imágenes sí están en el repo, pero no las están colocando sobre el README.md

**Comment by fullarukad** [comment]
profe ya revisamos en el README.md ya deben estar la imágenes,

**Comment by kala855** [comment]
Listo. Ya me renderizó bien las imágenes.
